(define (search-for-primes start count)
  (define (iter n found)
    (cond ((= found count) (newline) 'done)
          ((prime? n)
           (display n)
           (newline)
           (iter (+ n 1) (+ found 1)))
          (else (iter (+ n 1) found))))
  (iter start 0))